### ISSUE TITLE
This didn't work for me.

### ISSUE THREAD

**Issue by drewdrewthis** [akameco/jest-yaml-transform#3]
- version:
- `node` version:
- `npm` (or `yarn`) version:

**Do you want to request a *feature* or report a *bug*?:**

**What is the current behavior?:**
yml values came back empty

**What is the expected behavior?:**
The yml values come back for the right keys

**Suggested solution:**
https://github.com/danwang/yaml-jest

**Comment by drewdrewthis** [comment]
Sorry if this was blunt. But I figured it was better than just deleting this package and pretending like I didn't even try. Best of luck!

**Comment by akameco** [comment]
@drewdrewthis Thank you for reporting 😄

**Comment by 0vidiu** [comment]
This automatically flattens the parsed JSON object and it did not work for my use case. Maybe consider adding options? I had to write my own jest transformer following the Webpack yaml loader source example.

**Comment by vincerubinetti** [comment]
Anyone stumbling upon this, note the comment above.

With a yaml file like:

```yaml
- name: Team A
  members:
    - name: Jane Smith
    - name: Alex Smith
```

you'll get something like:

```json
{
  "0.name": "Team A",
  "0.members.0.name": "Jane Smith",
  "0.members.1.name": "Alex Smith",
}
```

In my estimation, this is useless to 99% of users. [`yaml-jest`](https://github.com/danwang/yaml-jest) on the other hand seems to work as expected. **Do not use this package**. I would even go far as to say that the creator of this package should delete it. It is the first to show up on google and other people will likely waste a lot of time debugging as I did. At the very least, there should be a giant warning in the readme saying that it flattens the structure.
